[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/', '@src/=src/', '@test/=test/', "@string-utils/=lib/solidity-stringutils/src/", "@bytes-utils/=lib/solidity-bytes-utils/contracts/"]
fs_permissions = [{ access = "read", path = "./test/signature.json"}, { access = "read", path = "./test/signer.json"}]
ffi=true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config